[config.wallpaper]
command = "wallpaper {{image}}"

[templates.termux]
input_path = '~/.config/matugen/templates/colors.properties'
output_path = '~/.termux/colors.properties'
post_hook = 'termux-reload-settings'

[templates.yazilua]
pre_hook = 'mkdir -p ~/.config/yazi/plugins/matugen.yazi'
input_path = '~/.config/matugen/templates/colors.lua'
output_path = '~/.config/yazi/plugins/matugen.yazi/main.lua'

[templates.yazi]
pre_hook = 'mkdir -p ~/.config/yazi/flavors/matugen.yazi'
input_path = '~/.config/matugen/templates/yazi.toml'
output_path = '~/.config/yazi/flavors/matugen.yazi/flavor.toml'

[templates.fastfetch]
input_path = '~/.config/matugen/templates/fastfetch.jsonc'
output_path = '~/.config/fastfetch/config.jsonc'

[templates.fish_prompt]
input_path = '~/.config/matugen/templates/fish_prompt.fish'
output_path = '~/.config/fish/functions/fish_prompt.fish'



